// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class events1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(events1));
        
        string IMigrationMetadata.Id
        {
            get { return "201305311435165_events1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
