// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class documents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documents));
        
        string IMigrationMetadata.Id
        {
            get { return "201305311753323_documents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
