// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Events3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Events3));
        
        string IMigrationMetadata.Id
        {
            get { return "201305311724393_Events-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
