// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class shares1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shares1));
        
        string IMigrationMetadata.Id
        {
            get { return "201307101448013_shares1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
