// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dividends : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dividends));
        
        string IMigrationMetadata.Id
        {
            get { return "201305292106421_dividends"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
