// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class documents2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documents2));
        
        string IMigrationMetadata.Id
        {
            get { return "201305311941152_documents-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
