// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newsSource1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsSource1));
        
        string IMigrationMetadata.Id
        {
            get { return "201305091432507_newsSource1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
