// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class stocks1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stocks1));
        
        string IMigrationMetadata.Id
        {
            get { return "201301130458567_stocks1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
