// <auto-generated />
namespace OPIMsys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class stocks2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stocks2));
        
        string IMigrationMetadata.Id
        {
            get { return "201301130501398_stocks2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
